# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegisteredStudentList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class RegisteredStudentListUI(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 488)
        self.classComboBox = QtWidgets.QComboBox(Dialog)
        self.classComboBox.setGeometry(QtCore.QRect(101, 30, 62, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.classComboBox.setFont(font)
        self.classComboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.studentTableView = QtWidgets.QTableView(Dialog)
        self.studentTableView.setGeometry(QtCore.QRect(20, 70, 711, 391))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.studentTableView.setFont(font)
        self.studentTableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Danh sách học sinh đã đăng ký"))
        self.label.setText(_translate("Dialog", "Lớp"))

