# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\StudentRecognizeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from image_widget import ImageWidget

class StudentRecognizeMainWindowUI(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(633, 708)
        font = QtGui.QFont()
        font.setPointSize(10)
        mainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.imgWidget = ImageWidget(self.centralwidget)
        self.imgWidget.setGeometry(QtCore.QRect(10, 10, 611, 361))
        self.imgWidget.setObjectName("widget")
        self.listViewAttendance = QtWidgets.QListView(self.centralwidget)
        self.listViewAttendance.setGeometry(QtCore.QRect(10, 470, 611, 192))
        self.listViewAttendance.setObjectName("listView")
        self.guideLabel = QtWidgets.QLabel(self.centralwidget)
        self.guideLabel.setGeometry(QtCore.QRect(20, 390, 601, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.guideLabel.setFont(font)
        self.guideLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.guideLabel.setObjectName("label")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 23))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Điểm danh học sinh"))
        self.guideLabel.setText(_translate("mainWindow", "TextLabel"))

