# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StudentRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(789, 499)
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 60, 311, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.idLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.idLineEdit)
        self.birthdayLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.birthdayLabel.setObjectName("birthdayLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.birthdayLabel)
        self.birthdayDateEdit = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.birthdayDateEdit.setObjectName("birthdayDateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.birthdayDateEdit)
        self.classLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.classLabel.setObjectName("classLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.classLabel)
        self.classLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.classLineEdit.setObjectName("classLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.classLineEdit)
        self.widget = ImageWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(380, 60, 361, 271))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(380, 379, 331, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(370, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 450, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(610, 450, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Đăng ký thông tin học sinh"))
        self.nameLabel.setText(_translate("Dialog", "Họ và Tên"))
        self.idLabel.setText(_translate("Dialog", "Mã học sinh"))
        self.birthdayLabel.setText(_translate("Dialog", "Ngày sinh"))
        self.classLabel.setText(_translate("Dialog", "Lớp học"))
        self.label.setText(_translate("Dialog", "Hướng dẫn sử dụng ..."))
        self.pushButton.setText(_translate("Dialog", "Lấy mẫu ảnh"))
        self.pushButton_2.setText(_translate("Dialog", "Lưu"))
        self.pushButton_3.setText(_translate("Dialog", "Hủy"))

from image_widget import ImageWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
